services:
  app:
    build:
      context: .
      target: dev
      args:
        APP_NAME: app
    image: app
    container_name: app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
